import { strict as assert } from 'node:assert';
import { createElement } from 'react';
import { renderToString } from 'react-dom/server';
import { MessageItem } from '../src/components/MessageItem';
import { ToolDetails, parseCommandOutput } from '../src/components/ToolDetails';
import { agentMessage, collectAgentRuns } from '../src/subagentView';
import { createInitialChatState, reduceChat } from '../src/state';
import { readDockLayout, movePanel } from '../src/dockLayout';
import { searchMatches, webResults } from '../src/toolPresentation';
import { setLocale } from '../src/i18n';
import type { FromExtensionMessage, SubagentTrace } from '../src/types';
setLocale('en');
const trace: SubagentTrace = { taskId:'task-a', profile:'explore', description:'Find auth', prompt:'Trace expiry', model:'child-model', tools:['read_file'], resumed:false, status:'cancelled', startedAt:1000, updatedAt:2000, endedAt:2000, toolCalls:2, inputTokens:123, outputTokens:45, entries:[
    {id:'intro', kind:'text', text:'Actual child narration <script>', startedAt:1000, endedAt:1100},
    {id:'read', kind:'tool', tool:'read_file', text:'{"path":"a.ts"}', output:'', isError:true, startedAt:1100, endedAt:1200},
    {id:'cmd', kind:'tool', tool:'run_terminal_command', text:'{"command":"npm test"}', live:'before cancellation', startedAt:1200, endedAt:2000},
] };
let state = createInitialChatState();
const post = (msg: FromExtensionMessage) => { state = reduceChat(state, msg); };
post({type:'startResponse'});
post({type:'toolCall', tool:'task', args:'{"subagent_type":"explore","description":"Find auth"}', callId:'parent-a'});
post({type:'toolCall', tool:'task', args:'{"subagent_type":"general"}', callId:'parent-b'});
post({type:'subagentState', callId:'parent-a', trace});
assert.equal(collectAgentRuns(state.messages)[0].trace, trace);
assert.equal(collectAgentRuns(state.messages)[1].status, 'queued');
const original = state;
post({type:'subagentState', callId:'stale-session-call', trace});
assert.equal(state, original);
post({type:'fullResponse', persian:'Final parent report'});
post({type:'startResponse'});
post({type:'subagentState', callId:'parent-a', trace:{...trace,status:'done'}});
assert.equal(collectAgentRuns(state.messages)[0].status, 'done', 'updates locate original calls across bubble boundaries');
assert.equal(collectAgentRuns(state.messages)[1].status, 'interrupted');
const message = agentMessage({...collectAgentRuns(state.messages)[0], trace, status:'cancelled'});
assert.equal(message.steps[1].result, '');
assert.ok(message.steps[1].isError);
assert.ok(message.steps[2].interrupted);
for (const locale of ['en','fa'] as const) {
    setLocale(locale);
    const html = renderToString(createElement(MessageItem,{message,observation:true, transcriptPrefs:{expand:{terminal:true,read:true}}}));
    assert.match(html, /Actual child narration &lt;script&gt;/);
    assert.doesNotMatch(html, /class="approval-card|icon-btn-mini|class="msg-footer|class="step running/);
    assert.match(html,/detail-interrupted/);
    assert.match(html,/before cancellation/);
    const activity = renderToString(createElement(MessageItem,{message,observation:true,activityOnly:true}));
    assert.doesNotMatch(activity,/Actual child narration/);
}
setLocale('en');
assert.deepEqual(parseCommandOutput('Exit code: 2\nSTDOUT:\n(empty)\nSTDERR:\nactual error\n'),{exit:'2',stdout:'',stderr:'actual error'});
assert.equal(parseCommandOutput('Error: cannot run\nSTDOUT:\npartial').stdout,'Error: cannot run\nSTDOUT:\npartial');
assert.deepEqual(searchMatches('C:\\project\\a.ts:38:first\nC:\\project\\a.ts:40:second\nb.ts:2:another')?.map(g => [g.path, g.lines.length]),[['C:\\project\\a.ts',2],['b.ts',1]]);
assert.equal(searchMatches('a.ts:1:one\nUnknown provider note'),null);
assert.equal(webResults('1. Docs\n   https://example.com/docs\n   First line\n   Second line\n\n2. Other\n   https://example.org\n   More')?.length,2);
assert.equal(webResults('1. Evil\n   javascript:alert(1)\n   No'),null);
assert.equal(webResults('Error: no access'),null);
const html = renderToString(createElement(ToolDetails,{call:{id:'read',kind:'toolCall',tool:'read_file',text:'{"path":"a.ts"}',result:'[a.ts - lines 38-39 of 100]\n<script>\nconst a = 1;'}}));
assert.match(html,/detail-source-line/); assert.match(html,/>38<\/span>/); assert.match(html,/&lt;script&gt;/); assert.match(html,/detail-arguments/);
const finalMessage = agentMessage({...collectAgentRuns(state.messages)[0],trace:{...trace,status:'done',entries:[{id:'final',kind:'text',text:'Final findings',html:'<p><strong>Final findings</strong></p>',startedAt:1,endedAt:2}]},status:'done'});
assert.match(renderToString(createElement(MessageItem,{message:finalMessage,observation:true})), /<strong>Final findings<\/strong>/);
const oldLayout = readDockLayout({version:1,main:['conversation','activity'],side:['changes']});
assert.deepEqual(oldLayout.main,['conversation','activity','agents','background']);
assert.deepEqual(movePanel(oldLayout,'agents','side').side,['changes','agents']);
post({type:'toolCall',tool:'run_terminal_command',args:'{"command":"npm test"}',callId:'bg'});
post({type:'terminalBackgrounded',callId:'bg',jobId:'job',byUser:true});
post({type:'backgroundJobs',jobs:[{jobId:'job',command:'npm test',running:true,uptimeSeconds:1}]});
const messagesBeforeOutput = state.messages.length;
post({type:'backgroundJobOutput',jobId:'foreign-session',output:'must be ignored'});
assert.equal(state.messages.length,messagesBeforeOutput);
post({type:'backgroundJobOutput',jobId:'job',output:'live background output'});
assert.equal(state.messages.at(-1)!.steps.at(-1)!.live,'live background output');
assert.equal(state.backgroundJobs[0].output,'live background output');
post({type:'backgroundJobs',jobs:[{jobId:'job',command:'npm test',running:true,uptimeSeconds:2}]});
assert.equal(state.backgroundJobs[0].output,'live background output','metadata refresh preserves streamed output');
post({type:'backgroundJobFinished',jobId:'job',status:'exited',exitCode:2,output:'Exit code: 2\nSTDOUT:\n(empty)\nSTDERR:\nfailure'});
post({type:'toolResult',tool:'run_terminal_command',callId:'bg',output:'started background job'});
const bg = state.messages.at(-1)!.steps.at(-1)!;
assert.equal(bg.background,undefined); assert.equal(bg.backgroundOutcome?.exitCode,2);
const bgHtml = renderToString(createElement(MessageItem,{message:state.messages.at(-1)!,transcriptPrefs:{expand:{terminal:true}}}));
assert.match(bgHtml,/failure/); assert.match(bgHtml,/step fail/); assert.doesNotMatch(bgHtml,/icon-btn-mini/);
console.log('agent observation: call identity, read-only runs, terminal states, safe artifacts, migrated docking and background completion passed');
