import { createElement } from 'react';
import { renderToString } from 'react-dom/server';
import { strict as assert } from 'node:assert';
import { MessageItem, ActivityTimeline } from '../src/components/MessageItem';
import { MessageList } from '../src/components/MessageList';
import { completedCommands } from '../src/components/CompletedOutcome';
import { ReviewDiff, reviewLines } from '../src/components/ReviewDiff';
import { setLocale } from '../src/i18n';
import { defaultDockLayout, movePanel, readDockLayout } from '../src/dockLayout';
import type { ChatMessage, Step } from '../src/types';
setLocale('en');
const call: Step = { id: 'edit', kind: 'toolCall', tool: 'apply_patch', text: JSON.stringify({path:'src/a.ts',patch:'<<<<<<< SEARCH\nold\n=======\nnew\n>>>>>>> REPLACE'}), result: 'Patch applied', callId: 'edit' };
const terminal: Step = { id: 'cmd', kind: 'toolCall', tool: 'run_terminal_command', text: '{"command":"npm test"}', result: 'STDOUT:\nfailed\nSTDERR:\n\nExit code: 1' };
const message: ChatMessage = { id: 'a', role: 'assistant', text: 'Finished.', createdAt: 1000, completedAt: 5000, status: 'done', steps: [{id:'intro',kind:'text',text:'Before tools',html:'<p>Before tools</p>'},call,terminal,{id:'final',kind:'text',text:'Final answer',html:'<p>Final answer</p>'}] };
const render = (m = message, extra = {}) => renderToString(createElement(MessageItem, { message:m,...extra }));
const done = render();
assert.match(done, /class="completed-steps"/);
assert.doesNotMatch(done, /<details[^>]*open=""/);
assert.doesNotMatch(done, /SEARCH|class="pill-diff"/);
assert.ok(done.indexOf('Before tools') < done.indexOf('completed-steps'));
assert.ok(done.indexOf('Final answer') > done.indexOf('completed-steps'));
assert.match(done, /compact-step failed/);
assert.match(done, /Exit 1/);
assert.doesNotMatch(done, /lucide-check/);
const activity = renderToString(createElement(ActivityTimeline, {messages:[message]}));
assert.match(activity, /class="pill-diff"/);
assert.doesNotMatch(activity, /Before tools/);
assert.doesNotMatch(activity, /Final answer/);
assert.match(activity, /class="activity-age"/);
assert.doesNotMatch(activity, /completed-steps/);
assert.doesNotMatch(render({...message,status:'streaming'}), /completed-steps/);
assert.doesNotMatch(render({...message,approval:{approval_id:'ap',approvals:[{tool_call_id:'call',tool_name:'write_file',args:{path:'a',content:'b'}}]}}), /completed-steps/);
assert.doesNotMatch(render({...message,steps:[{...terminal,background:{jobId:'job',byUser:true}}]}), /completed-steps/);
assert.deepEqual(completedCommands([terminal]),[{id:'cmd',command:'npm test',exit:'1'}]);
assert.deepEqual(completedCommands([{...terminal,result:'12 tests passed. Exit code 0.'}]),[]);
assert.deepEqual(completedCommands([{...terminal,result:'STDOUT:\nExit code: 0\n',background:{jobId:'job',byUser:true}}]),[]);
assert.deepEqual(completedCommands([{...terminal,tool:'read_file'}]),[]);
const user=(id:string,cp?:string):ChatMessage=>({id,cp,role:'user',text:id,steps:[],status:'done',createdAt:0});
const checkpoints=renderToString(createElement(MessageList,{messages:[user('u1','aaaaaaa'),{...message,id:'a1'},user('u2','bbbbbbb'),{...message,id:'a2'}],onScroll:()=>{},onPickSuggestion:()=>{},onReviewChanges:()=>{},onAskReview:()=>{},reviewSha:'bbbbbbb',reviewFiles:[{path:'second-turn.ts',added:3,removed:1,binary:false,untracked:false}]}));
assert.equal((checkpoints.match(/class="turn-outcome"/g)??[]).length,2);
assert.equal((checkpoints.match(/second-turn.ts/g)??[]).length,1);
const untracked=reviewLines({path:'new',kind:'text',before:'',after:'x\n'.repeat(10000),hunks:[{oldStart:1,newStart:1,oldCount:0,newCount:10000,removedLines:[],addedLines:Array(10000).fill('x')}]});
assert.equal(untracked.rows.length,400);
assert.equal(untracked.truncated,true);
const contexts=reviewLines({path:'a',kind:'text',before:'a\nb\nc\nd\ne\nf',after:'a\nB\nc\nD\ne\nf',hunks:[{oldStart:2,oldCount:1,newStart:2,newCount:1,removedLines:['b'],addedLines:['B']},{oldStart:4,oldCount:1,newStart:4,newCount:1,removedLines:['d'],addedLines:['D']}]});
assert.equal(contexts.rows.filter(row=>row.text==='c').length,1);
assert.equal(contexts.rows.filter(row=>row.text==='d').length,1);
assert.equal(contexts.truncated,false);
const unsafeCode = '<img src=x onerror="alert(1)">';
const safeDiff = renderToString(createElement(ReviewDiff, {file: {path:'unsafe.txt',kind:'text',before:'',after:unsafeCode,hunks:[{oldStart:1,oldCount:0,newStart:1,newCount:1,removedLines:[],addedLines:[unsafeCode]}]}}));
assert.doesNotMatch(safeDiff, /<img/);
assert.match(safeDiff, /&lt;img/);
console.log('work-surface render: completed logs, retained activity, approvals, jobs, real exits, checkpoint ownership, and bounded diffs passed');

// Corrupt saved layouts cannot hide a panel or move the pinned conversation.
for (const saved of [null, {}, {version: 2}, {version: 1, main: ['activity'], side: ['conversation', 'changes']}, {version: 1, main: ['conversation', 'activity'], side: ['activity']}, {version: 1, main: ['conversation', 'unknown'], side: ['changes']}]) {
    assert.deepEqual(readDockLayout(saved), defaultDockLayout());
}
let layout = movePanel(defaultDockLayout(), 'activity', 'side');
assert.deepEqual(layout.main, ['conversation']);
assert.deepEqual(layout.side, ['changes', 'activity']);
assert.equal(layout.sideActive, 'activity');
layout = movePanel(layout, 'changes', 'main');
assert.equal(layout.mainActive, 'changes');
layout = movePanel(layout, 'activity', 'main');
assert.equal(layout.sideActive, null);
assert.deepEqual(layout.side, []);
assert.deepEqual(readDockLayout(layout), layout);
assert.equal(movePanel(layout, 'conversation', 'side'), layout);
assert.equal(movePanel(layout, 'changes', 'main'), layout);
assert.equal(readDockLayout({...layout, mainActive: 'unknown'}).mainActive, 'conversation');

const withApproval = {...message, status: 'streaming' as const, approval: {approval_id:'pending',approvals:[{tool_call_id:'cmd',tool_name:'run_terminal_command',args:{command:'npm test'}}]}};
const observation = renderToString(createElement(ActivityTimeline, {messages:[withApproval,{...withApproval,id:'system-approval',role:'system' as const}], onApprovalDecision:()=>{}, onBackgroundTerminal:()=>{}, onKillBackground:()=>{}}));
assert.doesNotMatch(observation, /approval-card|Send to background|Stop background/);
assert.doesNotMatch(observation, /Final answer/);
assert.doesNotMatch(renderToString(createElement(ReviewDiff, {file:{path:'a.ts',kind:'text',before:'old',after:'new',hunks:[{oldStart:1,oldCount:1,newStart:1,newCount:1,removedLines:['old'],addedLines:['new']}]}})), /@@/);
